# Generated by Django 2.1.4 on 2018-12-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=45, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('doc_type', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=5)),
                ('student', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'api_documents',
                'ordering': ('create_at',),
            },
        ),
    ]
