# Generated by Django 2.1.4 on 2019-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=45, null=True)),
                ('path', models.SlugField(default=None, max_length=100, null=True)),
                ('doc_type', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=5)),
                ('student', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'api_v1_document',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='LogsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')])),
                ('change_message', models.TextField()),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs de documentos',
                'db_table': 'api_v1_logs',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('token', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'api_v1_token',
                'ordering': ('-create_at',),
            },
        ),
    ]
